### ISSUE TITLE
Error in Parceler setup

### ISSUE THREAD

**Issue by elbunuelo** [gvsucis/mobile-app-dev-book#11]
Found in commit 2f74f20 2017-05-04, the configuration for the parceler should read ```annotationProcessor 'org.parceler:parceler:1.1.6'``` instead of ```annotationProcessor 'org.parceler:parceler-api:1.1.6'```. As it is right now, gradle recognizes the annotation but doesn't know what to do with it, resulting in a very hard to debug situation.

**Comment by jengelsma** [comment]
Closed in commit dc5882a281f8dafefb78cf125b96363db1fb61b8 on private repo.
