### ISSUE TITLE
Minor typo on listing 9.28

### ISSUE THREAD

**Issue by elbunuelo** [gvsucis/mobile-app-dev-book#12]
Line 5 of listing 9.28 in commit 2f74f20 reads `Bitmap thumbnail = (Bitmap) date.getParcelable("data");` it should be `Bitmap thumbnail = (Bitmap) data.getParcelableExtra("data");` (It says "date" instead of "data" and "getParcelable" instead of "getParcelableExtra")

**Comment by jengelsma** [comment]
Closed with commit 521ea9ae8cf47af870c1f05e90e604fede7002bc in private repo.
