### ISSUE TITLE
Missing datatype in listing 9.30

### ISSUE THREAD

**Issue by elbunuelo** [gvsucis/mobile-app-dev-book#13]
Line 5 in listing 9.30 in commit 2f74f20 is missing the Uri datatype

**Comment by elbunuelo** [comment]
I just realized that mediaUri is a class attribute and therefore it does not need a datatype in the listing. However, listing 9.34 uses photoUri and then 9.35 goes back to mediaUri. I think that the three of them should use mediaUri

**Comment by jengelsma** [comment]
Agreed.  Updated in commit fc1f0e9be800232621ac0a40794b3a2ba67f3cbb on private repo.
