### ISSUE TITLE
Illustration about Web App, Hybrid, Native

### ISSUE THREAD

**Issue by skofgar** [gvsucis/mobile-app-dev-book#19]
**Git commit:** 49544a9 
**Date:** 2017-08-28

**Page:** 2:Figure 1.1

I think the illustration has some issues and I am proposing a few changes, please review: 

- the colors are a little hard to read (black on green).
- I took the liberty to add Ionic (using Cordova), which is fairly popular as far as I know.
- Xamarin and React Native do create native components, as possible. So I am wondering if you would like to highlight that.
- The screenshot used has red underlinings and a small typo about the iPhone IDE. It's called `Xcode` and not `xCode`. https://developer.apple.com/xcode/

Proposition: https://www.icloud.com/pages/0hzSQDeV2862lUipMQ21jTuZQ#Web_App_-_Hybrid_App_-_Native_App_Overview

You should be able to download it and export it to a png or equivalent.

**Comment by jengelsma** [comment]
Figure is much easier on the eyes!  Thanks.  👍

**Comment by skofgar** [comment]
Ok, make sure you're okay with the changes I made or just modify names/sentences ;)

**Comment by jengelsma** [comment]
Will be included in next revision.
