### ISSUE TITLE
Android status bar icons

### ISSUE THREAD

**Issue by josiahcampbell** [gvsucis/mobile-app-dev-book#2]
**Location:** Page 30, Line 4
**Git Commit:**  be9b0cf
**Issue:**  Extra information in Android status bar photos
 
<img src="https://cloud.githubusercontent.com/assets/9521010/22400341/13b7a85c-e580-11e6-9a7d-e263258394b1.png" height="367" width="408">

Using the demo mode will hide status bar notifications and other indicators. This setting can be found under:
`Settings > Developer Options > Demo mode > Enable Demo Mode and Show Demo Mode`

|  ![screenshot_20170128-173038](https://cloud.githubusercontent.com/assets/9521010/22400330/a562aa28-e57f-11e6-9fcb-024f6058fea2.png)  |  ![screenshot_20170128-173026](https://cloud.githubusercontent.com/assets/9521010/22400329/a55f2d80-e57f-11e6-9645-3ceef5af85dc.png) |
|---|---|

**Comment by jengelsma** [comment]
Thanks!

**Comment by jengelsma** [comment]
Noted, will update the Android images as we go with this option enabled.  Thanks!
