### ISSUE TITLE
ch09 - media confirm screen (android)

### ISSUE THREAD

**Issue by jengelsma** [gvsucis/mobile-app-dev-book#20]
After adding a video or photo to a journal, a confirmation screen is shown to allow the user to tag with a date / location.  In the android version these are implemented as generic numeric fields, should be date entry / google place picker to match iOS.   Possibly impacts Ch10 as well when audio type is added?

**Comment by dulimarta** [comment]
Fixed in 6c60c0691de1c75cf3d07351e04b53275817dcac
