### ISSUE TITLE
ch11 - sample code referred to in book is missing! (Android)

### ISSUE THREAD

**Issue by jengelsma** [gvsucis/mobile-app-dev-book#21]
The Android section of Ch11 has a notebox that explains the book will omit certain details for brevity (see screenshot below).  However, the code repository for this chapter does not have any of that code included! 
![image](https://user-images.githubusercontent.com/718259/37165538-e7eee8d2-22ca-11e8-8faa-cb223a6a09af.png)

**Comment by jengelsma** [comment]
will need to be added to ch12 and ch13 as well for completeness.

**Comment by dulimarta** [comment]
Fixed in a8e05bf154bfc4c76c5de5893969d0c88738ce84
