### ISSUE TITLE
ch12 - issues in Calendar view (Android)

### ISSUE THREAD

**Issue by jengelsma** [gvsucis/mobile-app-dev-book#23]
A couple of issues noticed in the calendar view a) all the dates in the calendar have marks on them even though they are not part of the trips displayed in the RecylerView below.  b) the RecyclerView shows sections (past present future) even when there are no entries in them.  That doesn't seem right... see attached screenshot example. 
![image](https://user-images.githubusercontent.com/718259/37166824-26d6582a-22ce-11e8-908c-e61363403c18.png)

**Comment by dulimarta** [comment]
Was not able to produce the issue. In the following screenshot, I created a past trip (Apr 3-26) and the calendar shows red dots on the correct date range.

![screenshot_1525462254](https://user-images.githubusercontent.com/3125417/39649442-caa6b226-4fb3-11e8-8161-8d6ef6fc5b39.png)
