### ISSUE TITLE
ch12-13 - FAB covers tab bar!  (Android)

### ISSUE THREAD

**Issue by jengelsma** [gvsucis/mobile-app-dev-book#25]
The FAB on the main screen occludes the tab bar!   Seems like a best practice would be to add this to the action bar and get rid of the FAB?  What do the Android UI guidelines call for here?

![image](https://user-images.githubusercontent.com/718259/37169976-9042aefe-22d7-11e8-8383-0a1cc82ddd9c.png)

**Comment by dulimarta** [comment]
Fixed in 74346103c99a1e52f0e00e157e379093d3305032
