### ISSUE TITLE
Odd wording on page 494

### ISSUE THREAD

**Issue by dwhitters** [gvsucis/mobile-app-dev-book#27]
![screenshot_2018-05-09_19-08-22](https://user-images.githubusercontent.com/7851196/39844436-19a2f2e6-53be-11e8-97dd-d2284c789785.png)

"Apple has either release a point or major release" doesn't make sense.

**Comment by dulimarta** [comment]
Should we change "point" to "minor"?

**Comment by dwhitters** [comment]
"Apple has either **released** a **minor or major** release." Would make sense to me.
