### ISSUE TITLE
iOS extension and delegate pattern introduction - commit be9b0cf

### ISSUE THREAD

**Issue by oneSIX** [gvsucis/mobile-app-dev-book#3]
At the bottom of page 48 the paragraph starting in line 13 introduces the concept of using Swift extensions when implementing  the UITextFieldDelegate. Listing 2.3 contains the complete code to implement this, upon initial read through this left a bit of ambiguity about how or why to use extensions. This was cleared up in the lecture/screencast from 2/1/2017 in class.

**Comment by jengelsma** [comment]
Appendix A.12 does introduce extensions and provide an example.  Would it help if we cited the appendix at this point, or should we flesh out the concept in more detail here?

**Comment by oneSIX** [comment]
Citing the appendix at this point would be the quick and easy way I think. There is only so much handholding that is necessary and going into detail in every potentially trivial area would make for a huge book.

**Comment by jengelsma** [comment]
This will be addressed in the next update.  Many thanks.
