### ISSUE TITLE
Page 502 Layout Issues

### ISSUE THREAD

**Issue by cyvannoy** [gvsucis/mobile-app-dev-book#34]
This sentence runs off the page. I am viewing the book as a pdf.

Note the functions stepBackward and stepForward are defined within the scope of **chooseStepFunctionV** yet when return from that function that can still be invoked outside of the function’s scope by way
of the return value.

**Comment by dwhitters** [comment]
Also, the function **stepForward** is spelled as **stepFoward** which I don't believe is intended.
