### ISSUE TITLE
Page 503 Possible Spelling

### ISSUE THREAD

**Issue by cyvannoy** [gvsucis/mobile-app-dev-book#35]
I may be wrong or just being nitpicky.

On Page 503: For example, Swift knows we are storing type String in the previous example, so there is **not** need to specify the types in our closure expression.

should it be no need?

P.S. I love that Roland and Camila made it into the book :)

**Comment by jengelsma** [comment]
Yep, that was  typo!  Thank you.    With all the feedback this class is giving me I may have to figure out how to introduce the cameo appearance of a few more students...  :-)
