### ISSUE TITLE
Page 9 Spelling

### ISSUE THREAD

**Issue by cyvannoy** [gvsucis/mobile-app-dev-book#38]
Simulators that run on the Mac desktop are available for a variety of Apple
products, including various **modles** of the iPhone, iPad, Apple Watch and Apple TV product
families.

models ?

**Comment by cyvannoy** [comment]
Once registered, a **develop** can provision his account with Xcode ( Xcode Preferences... and
then on the dialog window that is displayed click on Accounts)

developer ?

**Comment by dulimarta** [comment]
Fixed
