### ISSUE TITLE
Clarify example for recycling concept

### ISSUE THREAD

**Issue by josiahcampbell** [gvsucis/mobile-app-dev-book#5]
**Location:** Page 186, Line 9-33
**Git Commit:** be9b0cf
**Issue:**
The example given about computer graphics makes sense, but may be too specific of a comparison in this context. A solution may be to play more towards the concept of the object and (cell|viewholder) and how they are recycled.

**Comment by jengelsma** [comment]
Done.  Feel free to reopen if you don't think the current update adds the necessary clarity.
