### ISSUE TITLE
Database access

### ISSUE THREAD

**Issue by jocmp** [gvsucis/mobile-app-dev-book#7]
**Location:** Page 263, line 1, 2
**Git Commit:** f883199
**Issue:**
This line says that during debugging and development, you can modify R/W database rules. While this might be safe for initial development and toy apps, it opens a pandora's box later down the line in debugging a production application, even in a test database online.

The sample iOS app takes immediate advantage of authentication, where the rules are known, but can be left untouched.

**Comment by jengelsma** [comment]
Possible reactions to this feedback: 

1. Eliminate this altogether (e.g. turning off authentication).  The sample code that follows assumes access is authenticated. 
2. Leave it in, but call out the fact that this is potentially dangerous and not useful beyond an initial tirekicking session. 

Thoughts?
